// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#ifndef _WILLI_ELECTRIC_UI_H
#define _WILLI_ELECTRIC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_INICIO.h"
#include "screens/ui_HOME.h"
#include "screens/ui_CONFIG.h"
#include "screens/ui_PROGRAMADO.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * opacity_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * slideright_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * slideleft_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logoj2f_png);    // assets/logoJ2F.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_rgb_png);    // assets/RGB.png
LV_IMG_DECLARE(ui_img_gauge_velocidad_png);    // assets/gauge_velocidad.png
LV_IMG_DECLARE(ui_img_speed_indicator_png);    // assets/speed_indicator.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_icn_settings_png);    // assets/icn_settings.png
LV_IMG_DECLARE(ui_img_icn_reinit_png);    // assets/icn_reinit.png
LV_IMG_DECLARE(ui_img_icn_run_png);    // assets/icn_run.png
LV_IMG_DECLARE(ui_img_icn_clock_png);    // assets/icn_clock.png
LV_IMG_DECLARE(ui_img_icn_update_png);    // assets/icn_update.png
LV_IMG_DECLARE(ui_img_icn_x2_png);    // assets/icn_x2.png
LV_IMG_DECLARE(ui_img_txt_conectar_png);    // assets/txt_conectar.png
LV_IMG_DECLARE(ui_img_txt_desconectar_png);    // assets/txt_desconectar.png
LV_IMG_DECLARE(ui_img_icn_actualizar_png);    // assets/icn_actualizar.png
LV_IMG_DECLARE(ui_img_icn_series_png);    // assets/icn_series.png
LV_IMG_DECLARE(ui_img_icn_minus_png);    // assets/icn_minus.png
LV_IMG_DECLARE(ui_img_icn_plus_png);    // assets/icn_plus.png
LV_IMG_DECLARE(ui_img_icn_pasadas_png);    // assets/icn_pasadas.png
LV_IMG_DECLARE(ui_img_icn_modo_png);    // assets/icn_modo.png

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Big_2);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Medium_26);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);
LV_FONT_DECLARE(ui_font_Units);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
