// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void reinit_ent(lv_event_t * e);
void btnLibreOn(lv_event_t * e);
void btnProgramaOn(lv_event_t * e);
void service_postergar(lv_event_t * e);
void service_aceptar(lv_event_t * e);
void config_loaded(lv_event_t * e);
void change_to_home(lv_event_t * e);
void wifi_btn_toggle(lv_event_t * e);
void event_btn_start_ota(lv_event_t * e);
void event_btn_check_ota(lv_event_t * e);
void btnSetPointSeriesMinus(lv_event_t * e);
void btnSetPointSeriesPlus(lv_event_t * e);
void btnSetPointMacroPause(lv_event_t * e);
void btnSetPointPasadasMinus(lv_event_t * e);
void btnSetPointPasadasPlus(lv_event_t * e);
void btnSetPointMicroPauseMin(lv_event_t * e);
void btnSetPointMicroPauseSeg(lv_event_t * e);
void btnTimeModeClicked(lv_event_t * e);
void btnDistanceModeClicked(lv_event_t * e);
void btnSetPointDistancePasada(lv_event_t * e);
void btnSetPointTimePasadaMin(lv_event_t * e);
void btnSetPointTimePasadaSeg(lv_event_t * e);
void btnProgramOk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
