// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#ifndef UI_CONFIG_H
#define UI_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CONFIG
extern void ui_CONFIG_screen_init(void);
extern void ui_CONFIG_screen_destroy(void);
extern void ui_event_CONFIG(lv_event_t * e);
extern lv_obj_t * ui_CONFIG;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Dropdown1;
extern void ui_event_btnConfig2(lv_event_t * e);
extern lv_obj_t * ui_btnConfig2;
extern lv_obj_t * ui_lblNetTittle;
extern void ui_event_passArea(lv_event_t * e);
extern lv_obj_t * ui_passArea;
extern lv_obj_t * ui_imgWifi2;
extern lv_obj_t * ui_lblNetworkIP;
extern lv_obj_t * ui_lblFirmwareVersion;
extern lv_obj_t * ui_lblMac;
extern lv_obj_t * ui_lblOdoMaquina;
extern void ui_event_btnWifi(lv_event_t * e);
extern lv_obj_t * ui_btnWifi;
extern lv_obj_t * ui_lblInfo;
extern lv_obj_t * ui_lblNetName;
extern lv_obj_t * ui_lblOtaNotes;
extern void ui_event_btnOtaUpdate(lv_event_t * e);
extern lv_obj_t * ui_btnOtaUpdate;
extern void ui_event_btnOtaCheck(lv_event_t * e);
extern lv_obj_t * ui_btnOtaCheck;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_otaOverlay;
extern lv_obj_t * ui_lblOtaStatus;
extern lv_obj_t * ui_barOta;
extern lv_obj_t * ui_lblOtaPct;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

