// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#include "../ui.h"

lv_obj_t * ui_CONFIG = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_btnConfig2 = NULL;
lv_obj_t * ui_lblNetTittle = NULL;
lv_obj_t * ui_passArea = NULL;
lv_obj_t * ui_imgWifi2 = NULL;
lv_obj_t * ui_lblNetworkIP = NULL;
lv_obj_t * ui_lblFirmwareVersion = NULL;
lv_obj_t * ui_lblMac = NULL;
lv_obj_t * ui_lblOdoMaquina = NULL;
lv_obj_t * ui_btnWifi = NULL;
lv_obj_t * ui_lblInfo = NULL;
lv_obj_t * ui_lblNetName = NULL;
lv_obj_t * ui_lblOtaNotes = NULL;
lv_obj_t * ui_btnOtaUpdate = NULL;
lv_obj_t * ui_btnOtaCheck = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_otaOverlay = NULL;
lv_obj_t * ui_lblOtaStatus = NULL;
lv_obj_t * ui_barOta = NULL;
lv_obj_t * ui_lblOtaPct = NULL;
// event funtions
void ui_event_CONFIG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        config_loaded(e);
    }
}

void ui_event_btnConfig2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HOME_screen_init);
        change_to_home(e);
    }
}

void ui_event_passArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_btnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifi_btn_toggle(e);
    }
}

void ui_event_btnOtaUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        event_btn_start_ota(e);
        _ui_flag_modify(ui_otaOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_lblOtaNotes, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_btnWifi, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnConfig2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_btnOtaCheck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        event_btn_check_ota(e);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_CONFIG_screen_init(void)
{
    ui_CONFIG = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CONFIG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CONFIG, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONFIG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_CONFIG);
    lv_obj_set_width(ui_Panel7, 382);
    lv_obj_set_height(ui_Panel7, 306);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_CONFIG);
    lv_dropdown_set_options(ui_Dropdown1, "");
    lv_obj_set_width(ui_Dropdown1, 250);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, lv_pct(-43));
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnConfig2 = lv_btn_create(ui_CONFIG);
    lv_obj_set_width(ui_btnConfig2, lv_pct(10));
    lv_obj_set_height(ui_btnConfig2, lv_pct(15));
    lv_obj_set_x(ui_btnConfig2, lv_pct(-1));
    lv_obj_set_y(ui_btnConfig2, lv_pct(0));
    lv_obj_set_align(ui_btnConfig2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnConfig2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfig2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfig2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfig2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnConfig2, &ui_img_icn_x2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNetTittle = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblNetTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNetTittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNetTittle, -157);
    lv_obj_set_y(ui_lblNetTittle, lv_pct(-35));
    lv_obj_set_align(ui_lblNetTittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNetTittle, "RED\n\n\n\n\nCLAVE");
    lv_obj_set_style_text_color(ui_lblNetTittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNetTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passArea = lv_textarea_create(ui_CONFIG);
    lv_obj_set_width(ui_passArea, 250);
    lv_obj_set_height(ui_passArea, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_passArea, 0);
    lv_obj_set_y(ui_passArea, lv_pct(-27));
    lv_obj_set_align(ui_passArea, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_passArea, true);
    lv_textarea_set_password_mode(ui_passArea, true);
    lv_obj_set_style_text_font(ui_passArea, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWifi2 = lv_img_create(ui_CONFIG);
    lv_img_set_src(ui_imgWifi2, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_imgWifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWifi2, lv_pct(2));
    lv_obj_set_y(ui_imgWifi2, lv_pct(2));
    lv_obj_add_flag(ui_imgWifi2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_imgWifi2, lv_color_hex(0x525552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNetworkIP = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblNetworkIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNetworkIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNetworkIP, lv_pct(2));
    lv_obj_set_y(ui_lblNetworkIP, lv_pct(-24));
    lv_obj_set_align(ui_lblNetworkIP, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblNetworkIP, "IP");
    lv_obj_set_style_text_color(ui_lblNetworkIP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNetworkIP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFirmwareVersion = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblFirmwareVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFirmwareVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFirmwareVersion, lv_pct(2));
    lv_obj_set_y(ui_lblFirmwareVersion, lv_pct(-17));
    lv_obj_set_align(ui_lblFirmwareVersion, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblFirmwareVersion, "VER");
    lv_obj_set_style_text_color(ui_lblFirmwareVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFirmwareVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMac = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblMac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMac, lv_pct(2));
    lv_obj_set_y(ui_lblMac, lv_pct(-10));
    lv_obj_set_align(ui_lblMac, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblMac, "MAC");
    lv_obj_set_style_text_color(ui_lblMac, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOdoMaquina = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblOdoMaquina, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOdoMaquina, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOdoMaquina, lv_pct(2));
    lv_obj_set_y(ui_lblOdoMaquina, lv_pct(-3));
    lv_obj_set_align(ui_lblOdoMaquina, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblOdoMaquina, "DIAS");
    lv_obj_set_style_text_color(ui_lblOdoMaquina, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOdoMaquina, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifi = lv_btn_create(ui_CONFIG);
    lv_obj_set_height(ui_btnWifi, 72);
    lv_obj_set_width(ui_btnWifi, lv_pct(38));
    lv_obj_set_x(ui_btnWifi, lv_pct(0));
    lv_obj_set_y(ui_btnWifi, lv_pct(4));
    lv_obj_set_align(ui_btnWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifi, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_btnWifi, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWifi, lv_color_hex(0x4EB754), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnWifi, &ui_img_txt_conectar_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnWifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnWifi, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnWifi, lv_color_hex(0xF2CD6A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_btnWifi, &ui_img_txt_desconectar_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_btnWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnWifi, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblInfo = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblInfo, lv_pct(0));
    lv_obj_set_y(ui_lblInfo, lv_pct(-13));
    lv_obj_set_align(ui_lblInfo, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfo, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lblInfo, "");
    lv_obj_set_style_text_color(ui_lblInfo, lv_color_hex(0x00FF21), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfo, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNetName = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblNetName, lv_pct(21));
    lv_obj_set_height(ui_lblNetName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNetName, lv_pct(-38));
    lv_obj_set_y(ui_lblNetName, lv_pct(-34));
    lv_obj_set_align(ui_lblNetName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNetName, "NOMBRE DE RED ");
    lv_obj_set_style_text_font(ui_lblNetName, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOtaNotes = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblOtaNotes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOtaNotes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOtaNotes, -8);
    lv_obj_set_y(ui_lblOtaNotes, 113);
    lv_obj_set_align(ui_lblOtaNotes, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_lblOtaNotes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOtaNotes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOtaNotes, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnOtaUpdate = lv_btn_create(ui_CONFIG);
    lv_obj_set_width(ui_btnOtaUpdate, 225);
    lv_obj_set_height(ui_btnOtaUpdate, 77);
    lv_obj_set_x(ui_btnOtaUpdate, 0);
    lv_obj_set_y(ui_btnOtaUpdate, 194);
    lv_obj_set_align(ui_btnOtaUpdate, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnOtaUpdate, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOtaUpdate, lv_color_hex(0x42926A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOtaUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnOtaUpdate, &ui_img_icn_actualizar_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnOtaUpdate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnOtaUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnOtaCheck = lv_btn_create(ui_CONFIG);
    lv_obj_set_width(ui_btnOtaCheck, 119);
    lv_obj_set_height(ui_btnOtaCheck, 102);
    lv_obj_set_x(ui_btnOtaCheck, -334);
    lv_obj_set_y(ui_btnOtaCheck, -183);
    lv_obj_set_align(ui_btnOtaCheck, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btnOtaCheck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOtaCheck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_CONFIG);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_height(ui_Keyboard1, lv_pct(60));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_otaOverlay = lv_obj_create(ui_CONFIG);
    lv_obj_set_width(ui_otaOverlay, lv_pct(100));
    lv_obj_set_height(ui_otaOverlay, lv_pct(100));
    lv_obj_set_align(ui_otaOverlay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_otaOverlay, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_otaOverlay, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_otaOverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_otaOverlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_otaOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_otaOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOtaStatus = lv_label_create(ui_otaOverlay);
    lv_obj_set_width(ui_lblOtaStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOtaStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOtaStatus, 0);
    lv_obj_set_y(ui_lblOtaStatus, 8);
    lv_obj_set_align(ui_lblOtaStatus, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_color(ui_lblOtaStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOtaStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOtaStatus, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barOta = lv_bar_create(ui_otaOverlay);
    lv_bar_set_value(ui_barOta, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barOta, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barOta, lv_pct(75));
    lv_obj_set_height(ui_barOta, lv_pct(10));
    lv_obj_set_align(ui_barOta, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barOta, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barOta, lv_color_hex(0x949494), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barOta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barOta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barOta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barOta, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_barOta, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barOta, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblOtaPct = lv_label_create(ui_otaOverlay);
    lv_obj_set_width(ui_lblOtaPct, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOtaPct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblOtaPct, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblOtaPct, "");
    lv_obj_set_style_text_color(ui_lblOtaPct, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOtaPct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOtaPct, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnConfig2, ui_event_btnConfig2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passArea, ui_event_passArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifi, ui_event_btnWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOtaUpdate, ui_event_btnOtaUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOtaCheck, ui_event_btnOtaCheck, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_passArea);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CONFIG, ui_event_CONFIG, LV_EVENT_ALL, NULL);

}

void ui_CONFIG_screen_destroy(void)
{
    if(ui_CONFIG) lv_obj_del(ui_CONFIG);

    // NULL screen variables
    ui_CONFIG = NULL;
    ui_Panel7 = NULL;
    ui_Dropdown1 = NULL;
    ui_btnConfig2 = NULL;
    ui_lblNetTittle = NULL;
    ui_passArea = NULL;
    ui_imgWifi2 = NULL;
    ui_lblNetworkIP = NULL;
    ui_lblFirmwareVersion = NULL;
    ui_lblMac = NULL;
    ui_lblOdoMaquina = NULL;
    ui_btnWifi = NULL;
    ui_lblInfo = NULL;
    ui_lblNetName = NULL;
    ui_lblOtaNotes = NULL;
    ui_btnOtaUpdate = NULL;
    ui_btnOtaCheck = NULL;
    ui_Keyboard1 = NULL;
    ui_otaOverlay = NULL;
    ui_lblOtaStatus = NULL;
    ui_barOta = NULL;
    ui_lblOtaPct = NULL;

}
