// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#include "../ui.h"

lv_obj_t * ui_groupPausa;
lv_obj_t * ui_rgbRing;
lv_obj_t * ui_HOME = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Group_Gauge = NULL;
lv_obj_t * ui_rgbRing = NULL;
lv_obj_t * ui_imgGaugeSpeed = NULL;
lv_obj_t * ui_imgCursorSpeed = NULL;
lv_obj_t * ui_Group_Speed = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_lblSpeedUnit = NULL;
lv_obj_t * ui_lblSpeedNumber = NULL;
lv_obj_t * ui_Group_Ritmo = NULL;
lv_obj_t * ui_LabelVarRitm = NULL;
lv_obj_t * ui_Label_kmh4 = NULL;
lv_obj_t * ui_Group_control = NULL;
lv_obj_t * ui_Group_Real_Time2 = NULL;
lv_obj_t * ui_Group_Data_Inter = NULL;
lv_obj_t * ui_lblInterTittle = NULL;
lv_obj_t * ui_groupPtllEntrenaInter2 = NULL;
lv_obj_t * ui_lblTittleTipoPasada2 = NULL;
lv_obj_t * ui_groupPtllEntrenaInter = NULL;
lv_obj_t * ui_Series = NULL;
lv_obj_t * ui_lblNumSeries = NULL;
lv_obj_t * ui_Pasadas = NULL;
lv_obj_t * ui_lblNumPasadas = NULL;
lv_obj_t * ui_Group_Distance = NULL;
lv_obj_t * ui_lblDistanceTittle = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_lblDistanceNumber = NULL;
lv_obj_t * ui_lblDistanceUnit = NULL;
lv_obj_t * ui_Group_Time = NULL;
lv_obj_t * ui_lblTimeTittle = NULL;
lv_obj_t * ui_lblTimeNumber = NULL;
lv_obj_t * ui_Group_Calorias = NULL;
lv_obj_t * ui_lblCaloriasTittle = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_lblCaloriasNumber = NULL;
lv_obj_t * ui_lblCaloriasUnit = NULL;
lv_obj_t * ui_Group_Up = NULL;
lv_obj_t * ui_imgWifi = NULL;
lv_obj_t * ui_ContainerlblDataSup = NULL;
lv_obj_t * ui_lblTime = NULL;
lv_obj_t * ui_lblDate = NULL;
lv_obj_t * ui_btnConfig = NULL;
lv_obj_t * ui_Group_Settings_Down = NULL;
lv_obj_t * ui_groupReinitbtn = NULL;
lv_obj_t * ui_btnReinicio = NULL;
lv_obj_t * ui_Button_Group = NULL;
lv_obj_t * ui_btnRealTime = NULL;
lv_obj_t * ui_btnInter = NULL;
lv_obj_t * ui_groupPausa = NULL;
lv_obj_t * ui_lblTittlePausa = NULL;
lv_obj_t * ui_lblPausa = NULL;
lv_obj_t * ui_pnlServiceOdo = NULL;
lv_obj_t * ui_btnServicePostergar = NULL;
lv_obj_t * ui_lblPostergar = NULL;
lv_obj_t * ui_btnServiceAceptar = NULL;
lv_obj_t * ui_lblAceptar = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_lblOdoMaquina2 = NULL;
lv_obj_t * ui_dotOta = NULL;
// event funtions
void ui_event_btnConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONFIG, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CONFIG_screen_init);
    }
}

void ui_event_btnReinicio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        reinit_ent(e);
    }
}

void ui_event_btnRealTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnInter, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_btnRealTime, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_btnRealTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_lblInterTittle, target, "ENTRENA LIBRE", "");
    }
    if(event_code == LV_EVENT_CLICKED) {
        btnLibreOn(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        slideright_Animation(ui_lblDistanceNumber, 0);
        slideleft_Animation(ui_lblDistanceUnit, 0);
    }
}

void ui_event_btnInter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_btnInter, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnRealTime, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_btnRealTime, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_lblInterTittle, target, "PROGRAMADO", "");
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_PROGRAMADO, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_screen_init);
        btnProgramaOn(e);
    }
}

void ui_event_btnServicePostergar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        service_postergar(e);
        _ui_flag_modify(ui_pnlServiceOdo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_btnServiceAceptar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        service_aceptar(e);
        _ui_flag_modify(ui_pnlServiceOdo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_dotOta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONFIG, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CONFIG_screen_init);
    }
}

// build funtions

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HOME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HOME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HOME, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HOME, 13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_HOME);
    lv_img_set_src(ui_Image2, &ui_img_bg2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 450);

    ui_Group_Gauge = lv_obj_create(ui_HOME);
    lv_obj_remove_style_all(ui_Group_Gauge);
    lv_obj_set_width(ui_Group_Gauge, lv_pct(60));
    lv_obj_set_height(ui_Group_Gauge, lv_pct(100));
    lv_obj_set_x(ui_Group_Gauge, lv_pct(-1));
    lv_obj_set_y(ui_Group_Gauge, lv_pct(0));
    lv_obj_set_align(ui_Group_Gauge, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Group_Gauge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rgbRing = lv_obj_create(ui_Group_Gauge);
    lv_obj_set_width(ui_rgbRing, lv_pct(100));
    lv_obj_set_height(ui_rgbRing, lv_pct(100));
    lv_obj_set_x(ui_rgbRing, 1);
    lv_obj_set_y(ui_rgbRing, 1);
    lv_obj_set_align(ui_rgbRing, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rgbRing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rgbRing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rgbRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_rgbRing, &ui_img_rgb_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgGaugeSpeed = lv_img_create(ui_Group_Gauge);
    lv_img_set_src(ui_imgGaugeSpeed, &ui_img_gauge_velocidad_png);
    lv_obj_set_width(ui_imgGaugeSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgGaugeSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgGaugeSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgGaugeSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgGaugeSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgGaugeSpeed, 350);

    ui_imgCursorSpeed = lv_img_create(ui_Group_Gauge);
    lv_img_set_src(ui_imgCursorSpeed, &ui_img_speed_indicator_png);
    lv_obj_set_width(ui_imgCursorSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgCursorSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgCursorSpeed, lv_pct(0));
    lv_obj_set_y(ui_imgCursorSpeed, lv_pct(3));
    lv_obj_set_align(ui_imgCursorSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgCursorSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgCursorSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgCursorSpeed, 400);

    ui_Group_Speed = lv_obj_create(ui_Group_Gauge);
    lv_obj_remove_style_all(ui_Group_Speed);
    lv_obj_set_width(ui_Group_Speed, lv_pct(100));
    lv_obj_set_height(ui_Group_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Group_Speed, lv_pct(0));
    lv_obj_set_y(ui_Group_Speed, lv_pct(-10));
    lv_obj_set_align(ui_Group_Speed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Speed, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Speed, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Group_Speed);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -3);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSpeedUnit = lv_label_create(ui_Container1);
    lv_obj_set_height(ui_lblSpeedUnit, 25);
    lv_obj_set_width(ui_lblSpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lblSpeedUnit, lv_pct(-16));
    lv_obj_set_y(ui_lblSpeedUnit, lv_pct(-19));
    lv_obj_set_align(ui_lblSpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_lblSpeedUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSpeedUnit, &ui_font_Units, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSpeedNumber = lv_label_create(ui_Group_Speed);
    lv_obj_set_width(ui_lblSpeedNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSpeedNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSpeedNumber, lv_pct(-20));
    lv_obj_set_y(ui_lblSpeedNumber, lv_pct(-1));
    lv_obj_set_align(ui_lblSpeedNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeedNumber, "0.0");
    lv_obj_set_style_text_color(ui_lblSpeedNumber, lv_color_hex(0x34D399), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeedNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSpeedNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSpeedNumber, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Ritmo = lv_obj_create(ui_Group_Gauge);
    lv_obj_remove_style_all(ui_Group_Ritmo);
    lv_obj_set_width(ui_Group_Ritmo, lv_pct(100));
    lv_obj_set_height(ui_Group_Ritmo, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Group_Ritmo, lv_pct(0));
    lv_obj_set_y(ui_Group_Ritmo, lv_pct(23));
    lv_obj_set_align(ui_Group_Ritmo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Ritmo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Ritmo, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Ritmo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVarRitm = lv_label_create(ui_Group_Ritmo);
    lv_obj_set_width(ui_LabelVarRitm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarRitm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVarRitm, lv_pct(-37));
    lv_obj_set_y(ui_LabelVarRitm, lv_pct(37));
    lv_obj_set_align(ui_LabelVarRitm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVarRitm, "00'00\"");
    lv_obj_set_style_text_color(ui_LabelVarRitm, lv_color_hex(0xA78BFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarRitm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarRitm, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_kmh4 = lv_label_create(ui_Group_Ritmo);
    lv_obj_set_width(ui_Label_kmh4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_kmh4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_kmh4, lv_pct(-15));
    lv_obj_set_y(ui_Label_kmh4, lv_pct(45));
    lv_obj_set_align(ui_Label_kmh4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_kmh4, "min/km");
    lv_obj_set_style_text_color(ui_Label_kmh4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_kmh4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_kmh4, &ui_font_Units, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_control = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Group_control, lv_pct(102));
    lv_obj_set_height(ui_Group_control, lv_pct(108));
    lv_obj_set_x(ui_Group_control, 0);
    lv_obj_set_y(ui_Group_control, lv_pct(-2));
    lv_obj_set_align(ui_Group_control, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_control, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_control, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_control, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Real_Time2 = lv_obj_create(ui_Group_control);
    lv_obj_set_width(ui_Group_Real_Time2, lv_pct(48));
    lv_obj_set_height(ui_Group_Real_Time2, lv_pct(80));
    lv_obj_set_x(ui_Group_Real_Time2, lv_pct(0));
    lv_obj_set_y(ui_Group_Real_Time2, lv_pct(-2));
    lv_obj_set_align(ui_Group_Real_Time2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Group_Real_Time2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Real_Time2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Real_Time2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Real_Time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Real_Time2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Data_Inter = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Data_Inter, lv_pct(100));
    lv_obj_set_height(ui_Group_Data_Inter, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Group_Data_Inter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Data_Inter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Data_Inter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Data_Inter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Data_Inter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInterTittle = lv_label_create(ui_Group_Data_Inter);
    lv_obj_set_width(ui_lblInterTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblInterTittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblInterTittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInterTittle, "ENTRENA LIBRE");
    lv_obj_set_style_text_color(ui_lblInterTittle, lv_color_hex(0x4F9956), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInterTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInterTittle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInterTittle, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupPtllEntrenaInter2 = lv_obj_create(ui_Group_Data_Inter);
    lv_obj_remove_style_all(ui_groupPtllEntrenaInter2);
    lv_obj_set_width(ui_groupPtllEntrenaInter2, lv_pct(100));
    lv_obj_set_height(ui_groupPtllEntrenaInter2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_groupPtllEntrenaInter2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTittleTipoPasada2 = lv_label_create(ui_groupPtllEntrenaInter2);
    lv_obj_set_width(ui_lblTittleTipoPasada2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleTipoPasada2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTittleTipoPasada2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleTipoPasada2, "por TIEMPO");
    lv_obj_set_style_text_color(ui_lblTittleTipoPasada2, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleTipoPasada2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleTipoPasada2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleTipoPasada2, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupPtllEntrenaInter = lv_obj_create(ui_Group_Data_Inter);
    lv_obj_set_width(ui_groupPtllEntrenaInter, lv_pct(100));
    lv_obj_set_height(ui_groupPtllEntrenaInter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_groupPtllEntrenaInter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_groupPtllEntrenaInter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_groupPtllEntrenaInter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_groupPtllEntrenaInter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupPtllEntrenaInter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Series = lv_label_create(ui_groupPtllEntrenaInter);
    lv_obj_set_width(ui_Series, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Series, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Series, lv_pct(-15));
    lv_obj_set_y(ui_Series, lv_pct(0));
    lv_label_set_text(ui_Series, "Series: ");
    lv_obj_set_style_text_color(ui_Series, lv_color_hex(0x185DAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Series, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Series, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNumSeries = lv_label_create(ui_groupPtllEntrenaInter);
    lv_obj_set_width(ui_lblNumSeries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNumSeries, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNumSeries, 0);
    lv_obj_set_y(ui_lblNumSeries, -18);
    lv_obj_set_align(ui_lblNumSeries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNumSeries, "0");
    lv_obj_set_style_text_color(ui_lblNumSeries, lv_color_hex(0x185DAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNumSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNumSeries, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pasadas = lv_label_create(ui_groupPtllEntrenaInter);
    lv_obj_set_width(ui_Pasadas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pasadas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pasadas, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Pasadas, "   Pasadas:    ");
    lv_obj_set_style_text_color(ui_Pasadas, lv_color_hex(0xAC9D52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pasadas, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNumPasadas = lv_label_create(ui_groupPtllEntrenaInter);
    lv_obj_set_width(ui_lblNumPasadas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNumPasadas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblNumPasadas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNumPasadas, "0");
    lv_obj_set_style_text_color(ui_lblNumPasadas, lv_color_hex(0xAC9D52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNumPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNumPasadas, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Distance = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Distance, lv_pct(75));
    lv_obj_set_height(ui_Group_Distance, lv_pct(21));
    lv_obj_set_align(ui_Group_Distance, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Distance, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Distance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Distance, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Distance, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Distance, lv_color_hex(0x3B82F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Distance, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Group_Distance, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Group_Distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Group_Distance, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Distance, lv_color_hex(0x3B82F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Group_Distance, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceTittle = lv_label_create(ui_Group_Distance);
    lv_obj_set_height(ui_lblDistanceTittle, lv_pct(30));
    lv_obj_set_width(ui_lblDistanceTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_lblDistanceTittle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblDistanceTittle, "DISTANCIA");
    lv_obj_set_style_text_color(ui_lblDistanceTittle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceTittle, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Group_Distance);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(66));
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceNumber = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblDistanceNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistanceNumber, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_lblDistanceNumber, lv_pct(-10));
    lv_obj_set_y(ui_lblDistanceNumber, lv_pct(10));
    lv_obj_set_align(ui_lblDistanceNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDistanceNumber, "0");
    lv_obj_set_style_text_color(ui_lblDistanceNumber, lv_color_hex(0x60A5FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceNumber, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceUnit = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblDistanceUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistanceUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDistanceUnit, lv_pct(60));
    lv_obj_set_y(ui_lblDistanceUnit, lv_pct(30));
    lv_label_set_text(ui_lblDistanceUnit, "mt");
    lv_obj_set_style_text_color(ui_lblDistanceUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceUnit, &ui_font_Units, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Time = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Time, lv_pct(75));
    lv_obj_set_height(ui_Group_Time, lv_pct(21));
    lv_obj_set_align(ui_Group_Time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Time, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Time, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Time, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Time, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Group_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Group_Time, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Group_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Group_Time, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Time, lv_color_hex(0x757475), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Group_Time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeTittle = lv_label_create(ui_Group_Time);
    lv_obj_set_height(ui_lblTimeTittle, lv_pct(30));
    lv_obj_set_width(ui_lblTimeTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_lblTimeTittle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTimeTittle, "TIEMPO");
    lv_obj_set_style_text_color(ui_lblTimeTittle, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimeTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTimeTittle, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeNumber = lv_label_create(ui_Group_Time);
    lv_obj_set_width(ui_lblTimeNumber, lv_pct(100));
    lv_obj_set_height(ui_lblTimeNumber, lv_pct(60));
    lv_obj_set_x(ui_lblTimeNumber, lv_pct(0));
    lv_obj_set_y(ui_lblTimeNumber, lv_pct(10));
    lv_obj_set_align(ui_lblTimeNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTimeNumber, "00:00:00");
    lv_obj_set_style_text_color(ui_lblTimeNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimeNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTimeNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTimeNumber, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Calorias = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Calorias, lv_pct(75));
    lv_obj_set_height(ui_Group_Calorias, lv_pct(21));
    lv_obj_set_align(ui_Group_Calorias, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Calorias, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Calorias, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Calorias, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Group_Calorias, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Group_Calorias, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Calorias, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Group_Calorias, lv_color_hex(0xEA580C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Group_Calorias, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Group_Calorias, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Group_Calorias, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Group_Calorias, lv_color_hex(0xFB923C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Group_Calorias, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Group_Calorias, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Calorias, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Calorias, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Calorias, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Calorias, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCaloriasTittle = lv_label_create(ui_Group_Calorias);
    lv_obj_set_height(ui_lblCaloriasTittle, lv_pct(30));
    lv_obj_set_width(ui_lblCaloriasTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_lblCaloriasTittle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCaloriasTittle, "CALORÍAS");
    lv_obj_set_style_text_color(ui_lblCaloriasTittle, lv_color_hex(0x7E7C7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCaloriasTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCaloriasTittle, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Group_Calorias);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(60));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCaloriasNumber = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblCaloriasNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCaloriasNumber, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_lblCaloriasNumber, lv_pct(-10));
    lv_obj_set_y(ui_lblCaloriasNumber, lv_pct(10));
    lv_obj_set_align(ui_lblCaloriasNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCaloriasNumber, "0");
    lv_obj_set_style_text_color(ui_lblCaloriasNumber, lv_color_hex(0xFB923C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCaloriasNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCaloriasNumber, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCaloriasUnit = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblCaloriasUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCaloriasUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCaloriasUnit, lv_pct(60));
    lv_obj_set_y(ui_lblCaloriasUnit, lv_pct(30));
    lv_label_set_text(ui_lblCaloriasUnit, "kcal");
    lv_obj_set_style_text_color(ui_lblCaloriasUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCaloriasUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCaloriasUnit, &ui_font_Units, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Up = lv_obj_create(ui_Group_control);
    lv_obj_set_width(ui_Group_Up, lv_pct(98));
    lv_obj_set_height(ui_Group_Up, lv_pct(14));
    lv_obj_set_x(ui_Group_Up, lv_pct(1));
    lv_obj_set_y(ui_Group_Up, lv_pct(2));
    lv_obj_set_align(ui_Group_Up, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Group_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWifi = lv_img_create(ui_Group_Up);
    lv_img_set_src(ui_imgWifi, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_imgWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWifi, lv_pct(2));
    lv_obj_set_y(ui_imgWifi, lv_pct(-1));
    lv_obj_set_align(ui_imgWifi, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_imgWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgWifi, 350);
    lv_obj_set_style_img_recolor(ui_imgWifi, lv_color_hex(0x525552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerlblDataSup = lv_obj_create(ui_Group_Up);
    lv_obj_remove_style_all(ui_ContainerlblDataSup);
    lv_obj_set_width(ui_ContainerlblDataSup, lv_pct(41));
    lv_obj_set_height(ui_ContainerlblDataSup, lv_pct(100));
    lv_obj_set_y(ui_ContainerlblDataSup, 0);
    lv_obj_set_x(ui_ContainerlblDataSup, lv_pct(9));
    lv_obj_set_align(ui_ContainerlblDataSup, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_ContainerlblDataSup, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerlblDataSup, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerlblDataSup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTime = lv_label_create(ui_ContainerlblDataSup);
    lv_obj_set_width(ui_lblTime, lv_pct(30));
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTime, lv_pct(33));
    lv_obj_set_y(ui_lblTime, lv_pct(-15));
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "00:00");
    lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDate = lv_label_create(ui_ContainerlblDataSup);
    lv_obj_set_width(ui_lblDate, lv_pct(40));
    lv_obj_set_height(ui_lblDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDate, lv_pct(34));
    lv_obj_set_y(ui_lblDate, lv_pct(-20));
    lv_obj_set_align(ui_lblDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDate, "01/01/2000");
    lv_obj_set_style_text_color(ui_lblDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnConfig = lv_btn_create(ui_Group_Up);
    lv_obj_set_width(ui_btnConfig, lv_pct(10));
    lv_obj_set_height(ui_btnConfig, lv_pct(85));
    lv_obj_set_x(ui_btnConfig, lv_pct(1));
    lv_obj_set_y(ui_btnConfig, lv_pct(0));
    lv_obj_set_align(ui_btnConfig, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_btnConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnConfig, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnConfig, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig, lv_color_hex(0xFF0303), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_btnConfig, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Group_Settings_Down = lv_obj_create(ui_Group_control);
    lv_obj_set_width(ui_Group_Settings_Down, lv_pct(98));
    lv_obj_set_height(ui_Group_Settings_Down, lv_pct(14));
    lv_obj_set_x(ui_Group_Settings_Down, lv_pct(1));
    lv_obj_set_y(ui_Group_Settings_Down, lv_pct(1));
    lv_obj_set_align(ui_Group_Settings_Down, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Group_Settings_Down, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Group_Settings_Down, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Settings_Down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Settings_Down, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Settings_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupReinitbtn = lv_obj_create(ui_Group_Settings_Down);
    lv_obj_remove_style_all(ui_groupReinitbtn);
    lv_obj_set_width(ui_groupReinitbtn, lv_pct(40));
    lv_obj_set_height(ui_groupReinitbtn, lv_pct(100));
    lv_obj_set_align(ui_groupReinitbtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_groupReinitbtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_groupReinitbtn, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupReinitbtn, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupReinitbtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnReinicio = lv_btn_create(ui_groupReinitbtn);
    lv_obj_set_width(ui_btnReinicio, lv_pct(100));
    lv_obj_set_height(ui_btnReinicio, lv_pct(100));
    lv_obj_set_align(ui_btnReinicio, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btnReinicio, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReinicio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnReinicio, &ui_img_icn_reinit_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnReinicio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnReinicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnReinicio, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnReinicio, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnReinicio, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button_Group = lv_obj_create(ui_Group_Settings_Down);
    lv_obj_set_width(ui_Button_Group, lv_pct(60));
    lv_obj_set_height(ui_Button_Group, lv_pct(100));
    lv_obj_set_x(ui_Button_Group, -29);
    lv_obj_set_y(ui_Button_Group, lv_pct(12));
    lv_obj_set_align(ui_Button_Group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button_Group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button_Group, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRealTime = lv_btn_create(ui_Button_Group);
    lv_obj_set_width(ui_btnRealTime, lv_pct(45));
    lv_obj_set_height(ui_btnRealTime, lv_pct(90));
    lv_obj_set_x(ui_btnRealTime, -1);
    lv_obj_set_y(ui_btnRealTime, 1);
    lv_obj_set_align(ui_btnRealTime, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_btnRealTime, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_btnRealTime, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnRealTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRealTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnRealTime, &ui_img_icn_run_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnRealTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnRealTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnRealTime, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRealTime, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRealTime, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnInter = lv_btn_create(ui_Button_Group);
    lv_obj_set_width(ui_btnInter, lv_pct(40));
    lv_obj_set_height(ui_btnInter, lv_pct(89));
    lv_obj_set_x(ui_btnInter, 0);
    lv_obj_set_y(ui_btnInter, -1);
    lv_obj_set_align(ui_btnInter, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnInter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnInter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnInter, &ui_img_icn_clock_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnInter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnInter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnInter, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnInter, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnInter, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_groupPausa = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_groupPausa, lv_pct(50));
    lv_obj_set_height(ui_groupPausa, lv_pct(50));
    lv_obj_set_align(ui_groupPausa, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupPausa, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupPausa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_groupPausa, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_groupPausa, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupPausa, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_groupPausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_groupPausa, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_groupPausa, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittlePausa = lv_label_create(ui_groupPausa);
    lv_obj_set_width(ui_lblTittlePausa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittlePausa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittlePausa, 0);
    lv_obj_set_y(ui_lblTittlePausa, 12);
    lv_obj_set_align(ui_lblTittlePausa, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittlePausa, "PAUSA");
    lv_obj_set_style_text_color(ui_lblTittlePausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittlePausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittlePausa, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPausa = lv_label_create(ui_groupPausa);
    lv_obj_set_width(ui_lblPausa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPausa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPausa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPausa, "0");
    lv_obj_set_style_text_color(ui_lblPausa, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPausa, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlServiceOdo = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_pnlServiceOdo, lv_pct(90));
    lv_obj_set_height(ui_pnlServiceOdo, lv_pct(60));
    lv_obj_set_align(ui_pnlServiceOdo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlServiceOdo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlServiceOdo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pnlServiceOdo, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pnlServiceOdo, lv_color_hex(0xAF4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlServiceOdo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlServiceOdo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlServiceOdo, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlServiceOdo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pnlServiceOdo, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnServicePostergar = lv_btn_create(ui_pnlServiceOdo);
    lv_obj_set_width(ui_btnServicePostergar, lv_pct(30));
    lv_obj_set_height(ui_btnServicePostergar, lv_pct(20));
    lv_obj_set_x(ui_btnServicePostergar, lv_pct(-25));
    lv_obj_set_y(ui_btnServicePostergar, lv_pct(28));
    lv_obj_set_align(ui_btnServicePostergar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnServicePostergar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnServicePostergar, lv_color_hex(0x5C5555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnServicePostergar, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnServicePostergar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnServicePostergar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnServicePostergar, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnServicePostergar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnServicePostergar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnServicePostergar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnServicePostergar, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblPostergar = lv_label_create(ui_pnlServiceOdo);
    lv_obj_set_width(ui_lblPostergar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPostergar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPostergar, -179);
    lv_obj_set_y(ui_lblPostergar, 73);
    lv_obj_set_align(ui_lblPostergar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPostergar, "POSTERGAR");
    lv_obj_set_style_text_color(ui_lblPostergar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPostergar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPostergar, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnServiceAceptar = lv_btn_create(ui_pnlServiceOdo);
    lv_obj_set_width(ui_btnServiceAceptar, lv_pct(30));
    lv_obj_set_height(ui_btnServiceAceptar, lv_pct(20));
    lv_obj_set_x(ui_btnServiceAceptar, lv_pct(25));
    lv_obj_set_y(ui_btnServiceAceptar, lv_pct(28));
    lv_obj_set_align(ui_btnServiceAceptar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnServiceAceptar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnServiceAceptar, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnServiceAceptar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnServiceAceptar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnServiceAceptar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnServiceAceptar, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnServiceAceptar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnServiceAceptar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnServiceAceptar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnServiceAceptar, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblAceptar = lv_label_create(ui_pnlServiceOdo);
    lv_obj_set_width(ui_lblAceptar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAceptar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAceptar, 177);
    lv_obj_set_y(ui_lblAceptar, 73);
    lv_obj_set_align(ui_lblAceptar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAceptar, "ACEPTAR");
    lv_obj_set_style_text_color(ui_lblAceptar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAceptar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblAceptar, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_pnlServiceOdo);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, lv_pct(0));
    lv_obj_set_y(ui_Label3, lv_pct(-28));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ES NECESARIO REALIZAR MANTENIMIENTO");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOdoMaquina2 = lv_label_create(ui_pnlServiceOdo);
    lv_obj_set_width(ui_lblOdoMaquina2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOdoMaquina2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblOdoMaquina2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblOdoMaquina2, "");
    lv_obj_set_style_text_color(ui_lblOdoMaquina2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOdoMaquina2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOdoMaquina2, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dotOta = lv_btn_create(ui_HOME);
    lv_obj_set_width(ui_dotOta, 72);
    lv_obj_set_height(ui_dotOta, 61);
    lv_obj_set_x(ui_dotOta, -1);
    lv_obj_set_y(ui_dotOta, 42);
    lv_obj_add_flag(ui_dotOta, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_dotOta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dotOta, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_dotOta, &ui_img_icn_update_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnConfig, ui_event_btnConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnReinicio, ui_event_btnReinicio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRealTime, ui_event_btnRealTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnInter, ui_event_btnInter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnServicePostergar, ui_event_btnServicePostergar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnServiceAceptar, ui_event_btnServiceAceptar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dotOta, ui_event_dotOta, LV_EVENT_ALL, NULL);
    ui_rgbRing = ui_rgbRing;
    ui_groupPausa = ui_groupPausa;

}

void ui_HOME_screen_destroy(void)
{
    if(ui_HOME) lv_obj_del(ui_HOME);

    // NULL screen variables
    ui_HOME = NULL;
    ui_Image2 = NULL;
    ui_Group_Gauge = NULL;
    ui_rgbRing = NULL;
    ui_rgbRing = NULL;
    ui_imgGaugeSpeed = NULL;
    ui_imgCursorSpeed = NULL;
    ui_Group_Speed = NULL;
    ui_Container1 = NULL;
    ui_lblSpeedUnit = NULL;
    ui_lblSpeedNumber = NULL;
    ui_Group_Ritmo = NULL;
    ui_LabelVarRitm = NULL;
    ui_Label_kmh4 = NULL;
    ui_Group_control = NULL;
    ui_Group_Real_Time2 = NULL;
    ui_Group_Data_Inter = NULL;
    ui_lblInterTittle = NULL;
    ui_groupPtllEntrenaInter2 = NULL;
    ui_lblTittleTipoPasada2 = NULL;
    ui_groupPtllEntrenaInter = NULL;
    ui_Series = NULL;
    ui_lblNumSeries = NULL;
    ui_Pasadas = NULL;
    ui_lblNumPasadas = NULL;
    ui_Group_Distance = NULL;
    ui_lblDistanceTittle = NULL;
    ui_Panel1 = NULL;
    ui_lblDistanceNumber = NULL;
    ui_lblDistanceUnit = NULL;
    ui_Group_Time = NULL;
    ui_lblTimeTittle = NULL;
    ui_lblTimeNumber = NULL;
    ui_Group_Calorias = NULL;
    ui_lblCaloriasTittle = NULL;
    ui_Panel2 = NULL;
    ui_lblCaloriasNumber = NULL;
    ui_lblCaloriasUnit = NULL;
    ui_Group_Up = NULL;
    ui_imgWifi = NULL;
    ui_ContainerlblDataSup = NULL;
    ui_lblTime = NULL;
    ui_lblDate = NULL;
    ui_btnConfig = NULL;
    ui_Group_Settings_Down = NULL;
    ui_groupReinitbtn = NULL;
    ui_btnReinicio = NULL;
    ui_Button_Group = NULL;
    ui_btnRealTime = NULL;
    ui_btnInter = NULL;
    ui_groupPausa = NULL;
    ui_groupPausa = NULL;
    ui_lblTittlePausa = NULL;
    ui_lblPausa = NULL;
    ui_pnlServiceOdo = NULL;
    ui_btnServicePostergar = NULL;
    ui_lblPostergar = NULL;
    ui_btnServiceAceptar = NULL;
    ui_lblAceptar = NULL;
    ui_Label3 = NULL;
    ui_lblOdoMaquina2 = NULL;
    ui_dotOta = NULL;

}
