// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOME
extern void ui_HOME_screen_init(void);
extern void ui_HOME_screen_destroy(void);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_Group_Gauge;
extern lv_obj_t * ui_rgbRing;
extern lv_obj_t * ui_imgGaugeSpeed;
extern lv_obj_t * ui_imgCursorSpeed;
extern lv_obj_t * ui_Group_Speed;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_lblSpeedUnit;
extern lv_obj_t * ui_lblSpeedNumber;
extern lv_obj_t * ui_Group_Ritmo;
extern lv_obj_t * ui_LabelVarRitm;
extern lv_obj_t * ui_Label_kmh4;
extern lv_obj_t * ui_Group_control;
extern lv_obj_t * ui_Group_Real_Time2;
extern lv_obj_t * ui_Group_Data_Inter;
extern lv_obj_t * ui_lblInterTittle;
extern lv_obj_t * ui_groupPtllEntrenaInter2;
extern lv_obj_t * ui_lblTittleTipoPasada2;
extern lv_obj_t * ui_groupPtllEntrenaInter;
extern lv_obj_t * ui_Series;
extern lv_obj_t * ui_lblNumSeries;
extern lv_obj_t * ui_Pasadas;
extern lv_obj_t * ui_lblNumPasadas;
extern lv_obj_t * ui_Group_Distance;
extern lv_obj_t * ui_lblDistanceTittle;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_lblDistanceNumber;
extern lv_obj_t * ui_lblDistanceUnit;
extern lv_obj_t * ui_Group_Time;
extern lv_obj_t * ui_lblTimeTittle;
extern lv_obj_t * ui_lblTimeNumber;
extern lv_obj_t * ui_Group_Calorias;
extern lv_obj_t * ui_lblCaloriasTittle;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblCaloriasNumber;
extern lv_obj_t * ui_lblCaloriasUnit;
extern lv_obj_t * ui_Group_Up;
extern lv_obj_t * ui_imgWifi;
extern lv_obj_t * ui_ContainerlblDataSup;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_lblDate;
extern void ui_event_btnConfig(lv_event_t * e);
extern lv_obj_t * ui_btnConfig;
extern lv_obj_t * ui_Group_Settings_Down;
extern lv_obj_t * ui_groupReinitbtn;
extern void ui_event_btnReinicio(lv_event_t * e);
extern lv_obj_t * ui_btnReinicio;
extern lv_obj_t * ui_Button_Group;
extern void ui_event_btnRealTime(lv_event_t * e);
extern lv_obj_t * ui_btnRealTime;
extern void ui_event_btnInter(lv_event_t * e);
extern lv_obj_t * ui_btnInter;
extern lv_obj_t * ui_groupPausa;
extern lv_obj_t * ui_lblTittlePausa;
extern lv_obj_t * ui_lblPausa;
extern lv_obj_t * ui_pnlServiceOdo;
extern void ui_event_btnServicePostergar(lv_event_t * e);
extern lv_obj_t * ui_btnServicePostergar;
extern lv_obj_t * ui_lblPostergar;
extern void ui_event_btnServiceAceptar(lv_event_t * e);
extern lv_obj_t * ui_btnServiceAceptar;
extern lv_obj_t * ui_lblAceptar;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_lblOdoMaquina2;
extern void ui_event_dotOta(lv_event_t * e);
extern lv_obj_t * ui_dotOta;
// CUSTOM VARIABLES
extern lv_obj_t * ui_rgbRing;
extern lv_obj_t * ui_groupPausa;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

