// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#include "../ui.h"

lv_obj_t * ui_INICIO = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_INICIO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_OUT, 250, 5000, &ui_HOME_screen_init);
    }
}

// build funtions

void ui_INICIO_screen_init(void)
{
    ui_INICIO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_INICIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_INICIO, lv_color_hex(0x4AA44A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_INICIO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_INICIO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_INICIO, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_INICIO);
    lv_img_set_src(ui_Image1, &ui_img_logoj2f_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 350);

    lv_obj_add_event_cb(ui_INICIO, ui_event_INICIO, LV_EVENT_ALL, NULL);

}

void ui_INICIO_screen_destroy(void)
{
    if(ui_INICIO) lv_obj_del(ui_INICIO);

    // NULL screen variables
    ui_INICIO = NULL;
    ui_Image1 = NULL;

}
