// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#ifndef UI_PROGRAMADO_H
#define UI_PROGRAMADO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PROGRAMADO
extern void ui_PROGRAMADO_screen_init(void);
extern void ui_PROGRAMADO_screen_destroy(void);
extern lv_obj_t * ui_PROGRAMADO;
extern lv_obj_t * ui_PanelSup;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_PanelInfoTraining;
extern lv_obj_t * ui_lblInfoTraining;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_PanelMedio;
extern lv_obj_t * ui_PanelSeries;
extern lv_obj_t * ui_PanelTittleSeries;
extern lv_obj_t * ui_PanelSetSeries;
extern void ui_event_btnSetPointNumSeriesMinus(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointNumSeriesMinus;
extern lv_obj_t * ui_lblSetPointNumSeries;
extern void ui_event_btnSetPointNumSeriesPlus(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointNumSeriesPlus;
extern lv_obj_t * ui_ContainerTextMacroPausa;
extern lv_obj_t * ui_LabelPausaSeries;
extern lv_obj_t * ui_ContainerbtnMacroPause;
extern void ui_event_btnSetPointMacroPause(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointMacroPause;
extern lv_obj_t * ui_lblSetPointMacroPause;
extern lv_obj_t * ui_PanelPasadas;
extern lv_obj_t * ui_PanelTittlePasadas;
extern lv_obj_t * ui_PanelSetPasadas;
extern void ui_event_btnSetPointNumPasadasMinus(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointNumPasadasMinus;
extern lv_obj_t * ui_lblSetPointNumPasadas;
extern void ui_event_btnSetPointNumPasadasPlus(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointNumPasadasPlus;
extern lv_obj_t * ui_ContainerTextMicropausa;
extern lv_obj_t * ui_LabelPausaPasadas;
extern lv_obj_t * ui_ContainerbtnMicroPausa;
extern lv_obj_t * ui_Container2;
extern void ui_event_btnSetPointMicropausaMin(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointMicropausaMin;
extern lv_obj_t * ui_lblSetPointMicropausaMin;
extern lv_obj_t * ui_Container3;
extern void ui_event_btnSetPointMicropausaSeg(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointMicropausaSeg;
extern lv_obj_t * ui_lblSetPointMicropausaSeg;
extern lv_obj_t * ui_PanelModoPasada;
extern lv_obj_t * ui_PanelTittleModoPasada;
extern lv_obj_t * ui_PanelSetModo;
extern void ui_event_btnTimeMode(lv_event_t * e);
extern lv_obj_t * ui_btnTimeMode;
extern lv_obj_t * ui_lblTimeMode;
extern void ui_event_btnDistanceMode(lv_event_t * e);
extern lv_obj_t * ui_btnDistanceMode;
extern lv_obj_t * ui_lblDistanceMode;
extern lv_obj_t * ui_ContainerTextModo;
extern lv_obj_t * ui_lblDistanceModeOk;
extern lv_obj_t * ui_lblTimeModeOk;
extern lv_obj_t * ui_ContainerbtnMicroPausa2;
extern lv_obj_t * ui_ContainerDistancePasada;
extern void ui_event_btnSetPointDistancePasada(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointDistancePasada;
extern lv_obj_t * ui_lblSetPointDistancePasada;
extern lv_obj_t * ui_ContainerTiempoPasadaMin;
extern void ui_event_btnSetPointTimePasadaMin(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointTimePasadaMin;
extern lv_obj_t * ui_lblSetPointTimePasadaMin;
extern lv_obj_t * ui_ContainerTiempoPasadaSeg;
extern void ui_event_btnSetPointTimePasadaSeg(lv_event_t * e);
extern lv_obj_t * ui_btnSetPointTimePasadaSeg;
extern lv_obj_t * ui_lblSetPointTimePasadaSeg;
extern lv_obj_t * ui_PanelInferior;
extern void ui_event_btnOk(lv_event_t * e);
extern lv_obj_t * ui_btnOk;
extern lv_obj_t * ui_lblBtnOk;
// CUSTOM VARIABLES
extern lv_obj_t * ui_btnSetPointTimePasadaSeg;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

