// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_electric

#include "../ui.h"

lv_obj_t * ui_btnSetPointTimePasadaSeg;
lv_obj_t * ui_PROGRAMADO = NULL;
lv_obj_t * ui_PanelSup = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_PanelInfoTraining = NULL;
lv_obj_t * ui_lblInfoTraining = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_PanelMedio = NULL;
lv_obj_t * ui_PanelSeries = NULL;
lv_obj_t * ui_PanelTittleSeries = NULL;
lv_obj_t * ui_PanelSetSeries = NULL;
lv_obj_t * ui_btnSetPointNumSeriesMinus = NULL;
lv_obj_t * ui_lblSetPointNumSeries = NULL;
lv_obj_t * ui_btnSetPointNumSeriesPlus = NULL;
lv_obj_t * ui_ContainerTextMacroPausa = NULL;
lv_obj_t * ui_LabelPausaSeries = NULL;
lv_obj_t * ui_ContainerbtnMacroPause = NULL;
lv_obj_t * ui_btnSetPointMacroPause = NULL;
lv_obj_t * ui_lblSetPointMacroPause = NULL;
lv_obj_t * ui_PanelPasadas = NULL;
lv_obj_t * ui_PanelTittlePasadas = NULL;
lv_obj_t * ui_PanelSetPasadas = NULL;
lv_obj_t * ui_btnSetPointNumPasadasMinus = NULL;
lv_obj_t * ui_lblSetPointNumPasadas = NULL;
lv_obj_t * ui_btnSetPointNumPasadasPlus = NULL;
lv_obj_t * ui_ContainerTextMicropausa = NULL;
lv_obj_t * ui_LabelPausaPasadas = NULL;
lv_obj_t * ui_ContainerbtnMicroPausa = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_btnSetPointMicropausaMin = NULL;
lv_obj_t * ui_lblSetPointMicropausaMin = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_btnSetPointMicropausaSeg = NULL;
lv_obj_t * ui_lblSetPointMicropausaSeg = NULL;
lv_obj_t * ui_PanelModoPasada = NULL;
lv_obj_t * ui_PanelTittleModoPasada = NULL;
lv_obj_t * ui_PanelSetModo = NULL;
lv_obj_t * ui_btnTimeMode = NULL;
lv_obj_t * ui_lblTimeMode = NULL;
lv_obj_t * ui_btnDistanceMode = NULL;
lv_obj_t * ui_lblDistanceMode = NULL;
lv_obj_t * ui_ContainerTextModo = NULL;
lv_obj_t * ui_lblDistanceModeOk = NULL;
lv_obj_t * ui_lblTimeModeOk = NULL;
lv_obj_t * ui_ContainerbtnMicroPausa2 = NULL;
lv_obj_t * ui_ContainerDistancePasada = NULL;
lv_obj_t * ui_btnSetPointDistancePasada = NULL;
lv_obj_t * ui_lblSetPointDistancePasada = NULL;
lv_obj_t * ui_ContainerTiempoPasadaMin = NULL;
lv_obj_t * ui_btnSetPointTimePasadaMin = NULL;
lv_obj_t * ui_lblSetPointTimePasadaMin = NULL;
lv_obj_t * ui_ContainerTiempoPasadaSeg = NULL;
lv_obj_t * ui_btnSetPointTimePasadaSeg = NULL;
lv_obj_t * ui_lblSetPointTimePasadaSeg = NULL;
lv_obj_t * ui_PanelInferior = NULL;
lv_obj_t * ui_btnOk = NULL;
lv_obj_t * ui_lblBtnOk = NULL;
// event funtions
void ui_event_btnSetPointNumSeriesMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointSeriesMinus(e);
    }
}

void ui_event_btnSetPointNumSeriesPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointSeriesPlus(e);
    }
}

void ui_event_btnSetPointMacroPause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointMacroPause(e);
    }
}

void ui_event_btnSetPointNumPasadasMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointPasadasMinus(e);
    }
}

void ui_event_btnSetPointNumPasadasPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointPasadasPlus(e);
    }
}

void ui_event_btnSetPointMicropausaMin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointMicroPauseMin(e);
    }
}

void ui_event_btnSetPointMicropausaSeg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointMicroPauseSeg(e);
    }
}

void ui_event_btnTimeMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_lblTittleTipoPasada2, target, "por TIEMPO", "");
        _ui_state_modify(ui_btnDistanceMode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_btnTimeMode, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnDistanceMode, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_lblTimeModeOk, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_lblDistanceModeOk, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTiempoPasadaMin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContainerTiempoPasadaSeg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ContainerDistancePasada, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        btnTimeModeClicked(e);
    }
}

void ui_event_btnDistanceMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_lblTittleTipoPasada2, target, "por DISTANCIA", "");
        _ui_state_modify(ui_btnTimeMode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_btnDistanceMode, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnTimeMode, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_lblDistanceModeOk, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_lblTimeModeOk, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTiempoPasadaMin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTiempoPasadaSeg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerDistancePasada, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        btnDistanceModeClicked(e);
    }
}

void ui_event_btnSetPointDistancePasada(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointDistancePasada(e);
    }
}

void ui_event_btnSetPointTimePasadaMin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointTimePasadaMin(e);
    }
}

void ui_event_btnSetPointTimePasadaSeg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnSetPointTimePasadaSeg(e);
    }
}

void ui_event_btnOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnProgramOk(e);
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HOME_screen_init);
    }
}

// build funtions

void ui_PROGRAMADO_screen_init(void)
{
    ui_PROGRAMADO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PROGRAMADO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_PROGRAMADO, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PROGRAMADO, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_PROGRAMADO, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PROGRAMADO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSup = lv_obj_create(ui_PROGRAMADO);
    lv_obj_set_width(ui_PanelSup, lv_pct(100));
    lv_obj_set_height(ui_PanelSup, lv_pct(15));
    lv_obj_set_align(ui_PanelSup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSup, lv_color_hex(0x272C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSup, lv_color_hex(0x4A5062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSup, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSup, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_PanelSup);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "Configurar entrenamiento");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_PanelSup);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -8);
    lv_obj_set_align(ui_Label8, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label8, "-- Intervalado --");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_PROGRAMADO);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 100);
    lv_obj_set_height(ui_Container5, lv_pct(4));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelInfoTraining = lv_obj_create(ui_PROGRAMADO);
    lv_obj_set_width(ui_PanelInfoTraining, lv_pct(95));
    lv_obj_set_height(ui_PanelInfoTraining, lv_pct(10));
    lv_obj_set_align(ui_PanelInfoTraining, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInfoTraining, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelInfoTraining, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelInfoTraining, lv_color_hex(0x0F1821), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInfoTraining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInfoTraining, lv_color_hex(0x474A57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInfoTraining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelInfoTraining, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelInfoTraining, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelInfoTraining, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelInfoTraining, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelInfoTraining, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoTraining = lv_label_create(ui_PanelInfoTraining);
    lv_obj_set_width(ui_lblInfoTraining, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblInfoTraining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblInfoTraining, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInfoTraining, "Series: 1 (pausa 1 min) | Pasadas: 6 (pausa 00:30) | Modo: Tiempo 01:00");
    lv_obj_set_style_text_color(ui_lblInfoTraining, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoTraining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInfoTraining, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoTraining, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_PROGRAMADO);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 100);
    lv_obj_set_height(ui_Container6, lv_pct(2));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMedio = lv_obj_create(ui_PROGRAMADO);
    lv_obj_set_width(ui_PanelMedio, lv_pct(100));
    lv_obj_set_height(ui_PanelMedio, lv_pct(55));
    lv_obj_set_align(ui_PanelMedio, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelMedio, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelMedio, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMedio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMedio, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMedio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSeries = lv_obj_create(ui_PanelMedio);
    lv_obj_set_width(ui_PanelSeries, lv_pct(30));
    lv_obj_set_height(ui_PanelSeries, lv_pct(85));
    lv_obj_set_align(ui_PanelSeries, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelSeries, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelSeries, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelSeries, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSeries, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSeries, lv_color_hex(0x5C6171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelSeries, lv_color_hex(0x2F3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelSeries, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelSeries, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSeries, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSeries, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelSeries, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PanelSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PanelSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTittleSeries = lv_obj_create(ui_PanelSeries);
    lv_obj_set_width(ui_PanelTittleSeries, lv_pct(100));
    lv_obj_set_height(ui_PanelTittleSeries, lv_pct(20));
    lv_obj_set_align(ui_PanelTittleSeries, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTittleSeries, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTittleSeries, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTittleSeries, lv_color_hex(0x1E5CA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTittleSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTittleSeries, &ui_img_icn_series_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTittleSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTittleSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTittleSeries, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTittleSeries, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetSeries = lv_obj_create(ui_PanelSeries);
    lv_obj_set_width(ui_PanelSetSeries, lv_pct(90));
    lv_obj_set_height(ui_PanelSetSeries, lv_pct(25));
    lv_obj_set_align(ui_PanelSetSeries, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelSetSeries, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSetSeries, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetSeries, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetSeries, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetSeries, lv_color_hex(0x111518), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelSetSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelSetSeries, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelSetSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelSetSeries, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetPointNumSeriesMinus = lv_btn_create(ui_PanelSetSeries);
    lv_obj_set_width(ui_btnSetPointNumSeriesMinus, lv_pct(25));
    lv_obj_set_height(ui_btnSetPointNumSeriesMinus, lv_pct(100));
    lv_obj_set_align(ui_btnSetPointNumSeriesMinus, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointNumSeriesMinus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumSeriesMinus, lv_color_hex(0x202831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumSeriesMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnSetPointNumSeriesMinus, &ui_img_icn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnSetPointNumSeriesMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnSetPointNumSeriesMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointNumSeriesMinus, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointNumSeriesMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointNumSeriesMinus, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumSeriesMinus, lv_color_hex(0x185DAC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumSeriesMinus, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblSetPointNumSeries = lv_label_create(ui_PanelSetSeries);
    lv_obj_set_width(ui_lblSetPointNumSeries, lv_pct(50));
    lv_obj_set_height(ui_lblSetPointNumSeries, lv_pct(100));
    lv_obj_set_align(ui_lblSetPointNumSeries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointNumSeries, "1");
    lv_obj_set_style_text_color(ui_lblSetPointNumSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointNumSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSetPointNumSeries, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointNumSeries, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetPointNumSeriesPlus = lv_btn_create(ui_PanelSetSeries);
    lv_obj_set_width(ui_btnSetPointNumSeriesPlus, lv_pct(25));
    lv_obj_set_height(ui_btnSetPointNumSeriesPlus, lv_pct(100));
    lv_obj_set_align(ui_btnSetPointNumSeriesPlus, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointNumSeriesPlus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumSeriesPlus, lv_color_hex(0x202831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumSeriesPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnSetPointNumSeriesPlus, &ui_img_icn_plus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnSetPointNumSeriesPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnSetPointNumSeriesPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointNumSeriesPlus, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointNumSeriesPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointNumSeriesPlus, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumSeriesPlus, lv_color_hex(0x185DAC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumSeriesPlus, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ContainerTextMacroPausa = lv_obj_create(ui_PanelSeries);
    lv_obj_remove_style_all(ui_ContainerTextMacroPausa);
    lv_obj_set_width(ui_ContainerTextMacroPausa, lv_pct(100));
    lv_obj_set_height(ui_ContainerTextMacroPausa, lv_pct(20));
    lv_obj_set_align(ui_ContainerTextMacroPausa, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTextMacroPausa, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerTextMacroPausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerTextMacroPausa, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerTextMacroPausa, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerTextMacroPausa, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPausaSeries = lv_label_create(ui_ContainerTextMacroPausa);
    lv_obj_set_height(ui_LabelPausaSeries, lv_pct(50));
    lv_obj_set_width(ui_LabelPausaSeries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_LabelPausaSeries, 0);
    lv_obj_set_y(ui_LabelPausaSeries, lv_pct(30));
    lv_obj_set_align(ui_LabelPausaSeries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPausaSeries, "Pausa entre series");
    lv_obj_set_style_text_color(ui_LabelPausaSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPausaSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPausaSeries, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerbtnMacroPause = lv_obj_create(ui_PanelSeries);
    lv_obj_remove_style_all(ui_ContainerbtnMacroPause);
    lv_obj_set_width(ui_ContainerbtnMacroPause, lv_pct(90));
    lv_obj_set_height(ui_ContainerbtnMacroPause, lv_pct(20));
    lv_obj_set_align(ui_ContainerbtnMacroPause, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ContainerbtnMacroPause, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerbtnMacroPause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerbtnMacroPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerbtnMacroPause, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerbtnMacroPause, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetPointMacroPause = lv_btn_create(ui_ContainerbtnMacroPause);
    lv_obj_set_width(ui_btnSetPointMacroPause, lv_pct(60));
    lv_obj_set_height(ui_btnSetPointMacroPause, lv_pct(75));
    lv_obj_set_align(ui_btnSetPointMacroPause, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointMacroPause, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointMacroPause, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointMacroPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointMacroPause, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointMacroPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointMacroPause, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetPointMacroPause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetPointMacroPause, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSetPointMacroPause, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSetPointMacroPause, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointMacroPause, lv_color_hex(0x185DAC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointMacroPause, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblSetPointMacroPause = lv_label_create(ui_ContainerbtnMacroPause);
    lv_obj_set_width(ui_lblSetPointMacroPause, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSetPointMacroPause, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSetPointMacroPause, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointMacroPause, "1 min");
    lv_obj_set_style_text_color(ui_lblSetPointMacroPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointMacroPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointMacroPause, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPasadas = lv_obj_create(ui_PanelMedio);
    lv_obj_set_width(ui_PanelPasadas, lv_pct(30));
    lv_obj_set_height(ui_PanelPasadas, lv_pct(85));
    lv_obj_set_align(ui_PanelPasadas, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPasadas, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPasadas, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPasadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPasadas, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPasadas, lv_color_hex(0x5C6171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelPasadas, lv_color_hex(0x2F3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelPasadas, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelPasadas, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPasadas, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelPasadas, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelPasadas, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTittlePasadas = lv_obj_create(ui_PanelPasadas);
    lv_obj_set_width(ui_PanelTittlePasadas, lv_pct(100));
    lv_obj_set_height(ui_PanelTittlePasadas, lv_pct(20));
    lv_obj_set_align(ui_PanelTittlePasadas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTittlePasadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTittlePasadas, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTittlePasadas, lv_color_hex(0xA99F52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTittlePasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTittlePasadas, &ui_img_icn_pasadas_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTittlePasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTittlePasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTittlePasadas, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTittlePasadas, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetPasadas = lv_obj_create(ui_PanelPasadas);
    lv_obj_set_width(ui_PanelSetPasadas, lv_pct(90));
    lv_obj_set_height(ui_PanelSetPasadas, lv_pct(25));
    lv_obj_set_x(ui_PanelSetPasadas, 0);
    lv_obj_set_y(ui_PanelSetPasadas, -1);
    lv_obj_set_align(ui_PanelSetPasadas, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelSetPasadas, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelSetPasadas, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetPasadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetPasadas, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetPasadas, lv_color_hex(0x111518), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelSetPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelSetPasadas, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelSetPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelSetPasadas, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetPointNumPasadasMinus = lv_btn_create(ui_PanelSetPasadas);
    lv_obj_set_width(ui_btnSetPointNumPasadasMinus, lv_pct(25));
    lv_obj_set_height(ui_btnSetPointNumPasadasMinus, lv_pct(100));
    lv_obj_set_align(ui_btnSetPointNumPasadasMinus, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointNumPasadasMinus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumPasadasMinus, lv_color_hex(0x242B32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumPasadasMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnSetPointNumPasadasMinus, &ui_img_icn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnSetPointNumPasadasMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnSetPointNumPasadasMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointNumPasadasMinus, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointNumPasadasMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointNumPasadasMinus, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumPasadasMinus, lv_color_hex(0xAC9D52), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumPasadasMinus, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblSetPointNumPasadas = lv_label_create(ui_PanelSetPasadas);
    lv_obj_set_width(ui_lblSetPointNumPasadas, lv_pct(50));
    lv_obj_set_height(ui_lblSetPointNumPasadas, lv_pct(100));
    lv_obj_set_align(ui_lblSetPointNumPasadas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointNumPasadas, "6");
    lv_obj_set_style_text_color(ui_lblSetPointNumPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointNumPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSetPointNumPasadas, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointNumPasadas, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSetPointNumPasadasPlus = lv_btn_create(ui_PanelSetPasadas);
    lv_obj_set_width(ui_btnSetPointNumPasadasPlus, lv_pct(25));
    lv_obj_set_height(ui_btnSetPointNumPasadasPlus, lv_pct(100));
    lv_obj_set_align(ui_btnSetPointNumPasadasPlus, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointNumPasadasPlus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumPasadasPlus, lv_color_hex(0x242B32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumPasadasPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnSetPointNumPasadasPlus, &ui_img_icn_plus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnSetPointNumPasadasPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnSetPointNumPasadasPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointNumPasadasPlus, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointNumPasadasPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointNumPasadasPlus, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointNumPasadasPlus, lv_color_hex(0xAC9D52), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointNumPasadasPlus, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ContainerTextMicropausa = lv_obj_create(ui_PanelPasadas);
    lv_obj_remove_style_all(ui_ContainerTextMicropausa);
    lv_obj_set_width(ui_ContainerTextMicropausa, lv_pct(100));
    lv_obj_set_height(ui_ContainerTextMicropausa, lv_pct(20));
    lv_obj_set_align(ui_ContainerTextMicropausa, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTextMicropausa, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerTextMicropausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerTextMicropausa, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerTextMicropausa, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerTextMicropausa, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPausaPasadas = lv_label_create(ui_ContainerTextMicropausa);
    lv_obj_set_height(ui_LabelPausaPasadas, lv_pct(50));
    lv_obj_set_width(ui_LabelPausaPasadas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_LabelPausaPasadas, 0);
    lv_obj_set_y(ui_LabelPausaPasadas, lv_pct(30));
    lv_obj_set_align(ui_LabelPausaPasadas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPausaPasadas, "Pausa entre pasadas");
    lv_obj_set_style_text_color(ui_LabelPausaPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPausaPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPausaPasadas, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerbtnMicroPausa = lv_obj_create(ui_PanelPasadas);
    lv_obj_remove_style_all(ui_ContainerbtnMicroPausa);
    lv_obj_set_width(ui_ContainerbtnMicroPausa, lv_pct(90));
    lv_obj_set_height(ui_ContainerbtnMicroPausa, lv_pct(20));
    lv_obj_set_align(ui_ContainerbtnMicroPausa, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerbtnMicroPausa, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerbtnMicroPausa, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerbtnMicroPausa, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerbtnMicroPausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerbtnMicroPausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerbtnMicroPausa, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerbtnMicroPausa, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ContainerbtnMicroPausa);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(50));
    lv_obj_set_height(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetPointMicropausaMin = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_btnSetPointMicropausaMin, lv_pct(90));
    lv_obj_set_height(ui_btnSetPointMicropausaMin, lv_pct(75));
    lv_obj_set_align(ui_btnSetPointMicropausaMin, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointMicropausaMin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointMicropausaMin, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointMicropausaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointMicropausaMin, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointMicropausaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointMicropausaMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetPointMicropausaMin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetPointMicropausaMin, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSetPointMicropausaMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSetPointMicropausaMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointMicropausaMin, lv_color_hex(0xAC9D52), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointMicropausaMin, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblSetPointMicropausaMin = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lblSetPointMicropausaMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSetPointMicropausaMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSetPointMicropausaMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointMicropausaMin, "0 min");
    lv_obj_set_style_text_color(ui_lblSetPointMicropausaMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointMicropausaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSetPointMicropausaMin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointMicropausaMin, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_ContainerbtnMicroPausa);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(50));
    lv_obj_set_height(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetPointMicropausaSeg = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_btnSetPointMicropausaSeg, lv_pct(90));
    lv_obj_set_height(ui_btnSetPointMicropausaSeg, lv_pct(75));
    lv_obj_set_align(ui_btnSetPointMicropausaSeg, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointMicropausaSeg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointMicropausaSeg, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointMicropausaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointMicropausaSeg, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointMicropausaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointMicropausaSeg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetPointMicropausaSeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetPointMicropausaSeg, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSetPointMicropausaSeg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSetPointMicropausaSeg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSetPointMicropausaSeg = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblSetPointMicropausaSeg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSetPointMicropausaSeg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSetPointMicropausaSeg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointMicropausaSeg, "5 s");
    lv_obj_set_style_text_color(ui_lblSetPointMicropausaSeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointMicropausaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointMicropausaSeg, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelModoPasada = lv_obj_create(ui_PanelMedio);
    lv_obj_set_width(ui_PanelModoPasada, lv_pct(30));
    lv_obj_set_height(ui_PanelModoPasada, lv_pct(85));
    lv_obj_set_align(ui_PanelModoPasada, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelModoPasada, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelModoPasada, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelModoPasada, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelModoPasada, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelModoPasada, lv_color_hex(0x5C6171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelModoPasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelModoPasada, lv_color_hex(0x2F3644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelModoPasada, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelModoPasada, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelModoPasada, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelModoPasada, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelModoPasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelModoPasada, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelModoPasada, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelModoPasada, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelModoPasada, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelModoPasada, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelModoPasada, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTittleModoPasada = lv_obj_create(ui_PanelModoPasada);
    lv_obj_set_width(ui_PanelTittleModoPasada, lv_pct(100));
    lv_obj_set_height(ui_PanelTittleModoPasada, lv_pct(20));
    lv_obj_set_align(ui_PanelTittleModoPasada, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTittleModoPasada, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTittleModoPasada, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTittleModoPasada, lv_color_hex(0x4F3F88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTittleModoPasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTittleModoPasada, &ui_img_icn_modo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTittleModoPasada, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTittleModoPasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTittleModoPasada, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTittleModoPasada, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetModo = lv_obj_create(ui_PanelModoPasada);
    lv_obj_set_width(ui_PanelSetModo, lv_pct(95));
    lv_obj_set_height(ui_PanelSetModo, lv_pct(25));
    lv_obj_set_x(ui_PanelSetModo, 0);
    lv_obj_set_y(ui_PanelSetModo, -1);
    lv_obj_set_align(ui_PanelSetModo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetModo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetModo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetModo, lv_color_hex(0x111518), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetModo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelSetModo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelSetModo, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelSetModo, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelSetModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTimeMode = lv_btn_create(ui_PanelSetModo);
    lv_obj_set_width(ui_btnTimeMode, lv_pct(50));
    lv_obj_set_height(ui_btnTimeMode, lv_pct(100));
    lv_obj_set_align(ui_btnTimeMode, LV_ALIGN_LEFT_MID);
    lv_obj_add_state(ui_btnTimeMode, LV_STATE_CHECKED | LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_btnTimeMode, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_btnTimeMode, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTimeMode, lv_color_hex(0x202831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTimeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnTimeMode, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnTimeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnTimeMode, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTimeMode, lv_color_hex(0x32608E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnTimeMode, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblTimeMode = lv_label_create(ui_PanelSetModo);
    lv_obj_set_width(ui_lblTimeMode, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_lblTimeMode, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_lblTimeMode, 22);
    lv_obj_set_y(ui_lblTimeMode, 0);
    lv_obj_set_align(ui_lblTimeMode, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblTimeMode, "TIEMPO");
    lv_obj_set_style_text_color(ui_lblTimeMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTimeMode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTimeMode, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDistanceMode = lv_btn_create(ui_PanelSetModo);
    lv_obj_set_width(ui_btnDistanceMode, lv_pct(50));
    lv_obj_set_height(ui_btnDistanceMode, lv_pct(100));
    lv_obj_set_align(ui_btnDistanceMode, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_btnDistanceMode, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_btnDistanceMode, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnDistanceMode, lv_color_hex(0x242B32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDistanceMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnDistanceMode, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnDistanceMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnDistanceMode, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnDistanceMode, lv_color_hex(0x31618B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnDistanceMode, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lblDistanceMode = lv_label_create(ui_PanelSetModo);
    lv_obj_set_width(ui_lblDistanceMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistanceMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDistanceMode, -10);
    lv_obj_set_y(ui_lblDistanceMode, 0);
    lv_obj_set_align(ui_lblDistanceMode, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblDistanceMode, "DISTANCIA");
    lv_obj_set_style_text_color(ui_lblDistanceMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceMode, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTextModo = lv_obj_create(ui_PanelModoPasada);
    lv_obj_remove_style_all(ui_ContainerTextModo);
    lv_obj_set_width(ui_ContainerTextModo, lv_pct(100));
    lv_obj_set_height(ui_ContainerTextModo, lv_pct(20));
    lv_obj_set_align(ui_ContainerTextModo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTextModo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerTextModo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerTextModo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerTextModo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerTextModo, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceModeOk = lv_label_create(ui_ContainerTextModo);
    lv_obj_set_height(ui_lblDistanceModeOk, lv_pct(50));
    lv_obj_set_width(ui_lblDistanceModeOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lblDistanceModeOk, 0);
    lv_obj_set_y(ui_lblDistanceModeOk, lv_pct(30));
    lv_obj_set_align(ui_lblDistanceModeOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDistanceModeOk, "Distancia de pasada");
    lv_obj_add_flag(ui_lblDistanceModeOk, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_lblDistanceModeOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceModeOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceModeOk, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeModeOk = lv_label_create(ui_ContainerTextModo);
    lv_obj_set_height(ui_lblTimeModeOk, lv_pct(50));
    lv_obj_set_width(ui_lblTimeModeOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lblTimeModeOk, 0);
    lv_obj_set_y(ui_lblTimeModeOk, lv_pct(30));
    lv_obj_set_align(ui_lblTimeModeOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTimeModeOk, "Tiempo de pasada");
    lv_obj_set_style_text_color(ui_lblTimeModeOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimeModeOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTimeModeOk, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerbtnMicroPausa2 = lv_obj_create(ui_PanelModoPasada);
    lv_obj_remove_style_all(ui_ContainerbtnMicroPausa2);
    lv_obj_set_width(ui_ContainerbtnMicroPausa2, lv_pct(90));
    lv_obj_set_height(ui_ContainerbtnMicroPausa2, lv_pct(20));
    lv_obj_set_align(ui_ContainerbtnMicroPausa2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerbtnMicroPausa2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerbtnMicroPausa2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerbtnMicroPausa2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerbtnMicroPausa2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerbtnMicroPausa2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerbtnMicroPausa2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerbtnMicroPausa2, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDistancePasada = lv_obj_create(ui_ContainerbtnMicroPausa2);
    lv_obj_remove_style_all(ui_ContainerDistancePasada);
    lv_obj_set_width(ui_ContainerDistancePasada, lv_pct(90));
    lv_obj_set_height(ui_ContainerDistancePasada, lv_pct(100));
    lv_obj_set_align(ui_ContainerDistancePasada, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerDistancePasada, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerDistancePasada, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetPointDistancePasada = lv_btn_create(ui_ContainerDistancePasada);
    lv_obj_set_width(ui_btnSetPointDistancePasada, lv_pct(90));
    lv_obj_set_height(ui_btnSetPointDistancePasada, lv_pct(75));
    lv_obj_set_align(ui_btnSetPointDistancePasada, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointDistancePasada, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointDistancePasada, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointDistancePasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointDistancePasada, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointDistancePasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointDistancePasada, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetPointDistancePasada, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetPointDistancePasada, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSetPointDistancePasada, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSetPointDistancePasada, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSetPointDistancePasada = lv_label_create(ui_ContainerDistancePasada);
    lv_obj_set_width(ui_lblSetPointDistancePasada, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSetPointDistancePasada, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSetPointDistancePasada, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointDistancePasada, "100 mt");
    lv_obj_set_style_text_color(ui_lblSetPointDistancePasada, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointDistancePasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointDistancePasada, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTiempoPasadaMin = lv_obj_create(ui_ContainerbtnMicroPausa2);
    lv_obj_remove_style_all(ui_ContainerTiempoPasadaMin);
    lv_obj_set_width(ui_ContainerTiempoPasadaMin, lv_pct(50));
    lv_obj_set_height(ui_ContainerTiempoPasadaMin, lv_pct(100));
    lv_obj_set_align(ui_ContainerTiempoPasadaMin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTiempoPasadaMin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetPointTimePasadaMin = lv_btn_create(ui_ContainerTiempoPasadaMin);
    lv_obj_set_width(ui_btnSetPointTimePasadaMin, lv_pct(90));
    lv_obj_set_height(ui_btnSetPointTimePasadaMin, lv_pct(75));
    lv_obj_set_align(ui_btnSetPointTimePasadaMin, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointTimePasadaMin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointTimePasadaMin, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointTimePasadaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointTimePasadaMin, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointTimePasadaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointTimePasadaMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetPointTimePasadaMin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetPointTimePasadaMin, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSetPointTimePasadaMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSetPointTimePasadaMin, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointTimePasadaMin, lv_color_hex(0x4A3C8B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnSetPointTimePasadaMin, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblSetPointTimePasadaMin = lv_label_create(ui_ContainerTiempoPasadaMin);
    lv_obj_set_width(ui_lblSetPointTimePasadaMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSetPointTimePasadaMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSetPointTimePasadaMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointTimePasadaMin, "0 min");
    lv_obj_set_style_text_color(ui_lblSetPointTimePasadaMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointTimePasadaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSetPointTimePasadaMin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointTimePasadaMin, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTiempoPasadaSeg = lv_obj_create(ui_ContainerbtnMicroPausa2);
    lv_obj_remove_style_all(ui_ContainerTiempoPasadaSeg);
    lv_obj_set_width(ui_ContainerTiempoPasadaSeg, lv_pct(50));
    lv_obj_set_height(ui_ContainerTiempoPasadaSeg, lv_pct(100));
    lv_obj_set_align(ui_ContainerTiempoPasadaSeg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTiempoPasadaSeg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetPointTimePasadaSeg = lv_btn_create(ui_ContainerTiempoPasadaSeg);
    lv_obj_set_width(ui_btnSetPointTimePasadaSeg, lv_pct(90));
    lv_obj_set_height(ui_btnSetPointTimePasadaSeg, lv_pct(75));
    lv_obj_set_align(ui_btnSetPointTimePasadaSeg, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnSetPointTimePasadaSeg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSetPointTimePasadaSeg, lv_color_hex(0x293441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetPointTimePasadaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSetPointTimePasadaSeg, lv_color_hex(0x4A4C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSetPointTimePasadaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSetPointTimePasadaSeg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetPointTimePasadaSeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetPointTimePasadaSeg, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSetPointTimePasadaSeg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSetPointTimePasadaSeg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSetPointTimePasadaSeg = lv_label_create(ui_ContainerTiempoPasadaSeg);
    lv_obj_set_width(ui_lblSetPointTimePasadaSeg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSetPointTimePasadaSeg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSetPointTimePasadaSeg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSetPointTimePasadaSeg, "10 s");
    lv_obj_set_style_text_color(ui_lblSetPointTimePasadaSeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSetPointTimePasadaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSetPointTimePasadaSeg, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInferior = lv_obj_create(ui_PROGRAMADO);
    lv_obj_set_width(ui_PanelInferior, lv_pct(100));
    lv_obj_set_height(ui_PanelInferior, lv_pct(15));
    lv_obj_set_align(ui_PanelInferior, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInferior, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInferior, lv_color_hex(0x202C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInferior, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInferior, lv_color_hex(0x4A5062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInferior, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelInferior, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelInferior, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnOk = lv_btn_create(ui_PanelInferior);
    lv_obj_set_width(ui_btnOk, lv_pct(25));
    lv_obj_set_height(ui_btnOk, lv_pct(80));
    lv_obj_set_align(ui_btnOk, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnOk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk, lv_color_hex(0x4EA44E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOk, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnOk, lv_color_hex(0xA9DFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnOk, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnOk, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnOk, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnOk, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnOk, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnOk, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk, lv_color_hex(0x00FF1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnOk, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblBtnOk = lv_label_create(ui_PanelInferior);
    lv_obj_set_width(ui_lblBtnOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtnOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBtnOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtnOk, "Aceptar");
    lv_obj_set_style_text_color(ui_lblBtnOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBtnOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBtnOk, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnSetPointNumSeriesMinus, ui_event_btnSetPointNumSeriesMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointNumSeriesPlus, ui_event_btnSetPointNumSeriesPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointMacroPause, ui_event_btnSetPointMacroPause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointNumPasadasMinus, ui_event_btnSetPointNumPasadasMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointNumPasadasPlus, ui_event_btnSetPointNumPasadasPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointMicropausaMin, ui_event_btnSetPointMicropausaMin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointMicropausaSeg, ui_event_btnSetPointMicropausaSeg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTimeMode, ui_event_btnTimeMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDistanceMode, ui_event_btnDistanceMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointDistancePasada, ui_event_btnSetPointDistancePasada, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointTimePasadaMin, ui_event_btnSetPointTimePasadaMin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetPointTimePasadaSeg, ui_event_btnSetPointTimePasadaSeg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOk, ui_event_btnOk, LV_EVENT_ALL, NULL);
    ui_btnSetPointTimePasadaSeg = ui_btnSetPointTimePasadaSeg;

}

void ui_PROGRAMADO_screen_destroy(void)
{
    if(ui_PROGRAMADO) lv_obj_del(ui_PROGRAMADO);

    // NULL screen variables
    ui_PROGRAMADO = NULL;
    ui_PanelSup = NULL;
    ui_Label6 = NULL;
    ui_Label8 = NULL;
    ui_Container5 = NULL;
    ui_PanelInfoTraining = NULL;
    ui_lblInfoTraining = NULL;
    ui_Container6 = NULL;
    ui_PanelMedio = NULL;
    ui_PanelSeries = NULL;
    ui_PanelTittleSeries = NULL;
    ui_PanelSetSeries = NULL;
    ui_btnSetPointNumSeriesMinus = NULL;
    ui_lblSetPointNumSeries = NULL;
    ui_btnSetPointNumSeriesPlus = NULL;
    ui_ContainerTextMacroPausa = NULL;
    ui_LabelPausaSeries = NULL;
    ui_ContainerbtnMacroPause = NULL;
    ui_btnSetPointMacroPause = NULL;
    ui_lblSetPointMacroPause = NULL;
    ui_PanelPasadas = NULL;
    ui_PanelTittlePasadas = NULL;
    ui_PanelSetPasadas = NULL;
    ui_btnSetPointNumPasadasMinus = NULL;
    ui_lblSetPointNumPasadas = NULL;
    ui_btnSetPointNumPasadasPlus = NULL;
    ui_ContainerTextMicropausa = NULL;
    ui_LabelPausaPasadas = NULL;
    ui_ContainerbtnMicroPausa = NULL;
    ui_Container2 = NULL;
    ui_btnSetPointMicropausaMin = NULL;
    ui_lblSetPointMicropausaMin = NULL;
    ui_Container3 = NULL;
    ui_btnSetPointMicropausaSeg = NULL;
    ui_lblSetPointMicropausaSeg = NULL;
    ui_PanelModoPasada = NULL;
    ui_PanelTittleModoPasada = NULL;
    ui_PanelSetModo = NULL;
    ui_btnTimeMode = NULL;
    ui_lblTimeMode = NULL;
    ui_btnDistanceMode = NULL;
    ui_lblDistanceMode = NULL;
    ui_ContainerTextModo = NULL;
    ui_lblDistanceModeOk = NULL;
    ui_lblTimeModeOk = NULL;
    ui_ContainerbtnMicroPausa2 = NULL;
    ui_ContainerDistancePasada = NULL;
    ui_btnSetPointDistancePasada = NULL;
    ui_lblSetPointDistancePasada = NULL;
    ui_ContainerTiempoPasadaMin = NULL;
    ui_btnSetPointTimePasadaMin = NULL;
    ui_lblSetPointTimePasadaMin = NULL;
    ui_ContainerTiempoPasadaSeg = NULL;
    ui_btnSetPointTimePasadaSeg = NULL;
    ui_btnSetPointTimePasadaSeg = NULL;
    ui_lblSetPointTimePasadaSeg = NULL;
    ui_PanelInferior = NULL;
    ui_btnOk = NULL;
    ui_lblBtnOk = NULL;

}
